---
title: "p8105_hw5_ab6168"
author: "Angelica Bailey"
date: "2025-11-05"
output: github_document
---

```{r}
library(tidyverse)
set.seed(1)
```


## Problem 1

Writing function:
```{r}
#n: number of people in the group
#return true if at least two people share a birthday, false otherwise

birthday_match = function(n) {
  #randomly drawing n birthdays from 1 to 365
  birthdays = sample(1:365, size = n, replace = TRUE) 
  
  return(any(duplicated(birthdays)))
}

```


Creating data frame
```{r}
simulation_results = data.frame(
  group_size = 2:50,
  probability = numeric(length(group_size)) #initialize column of zeros
)
```

Running simulations
```{r}
for (i in 1:nrow(simulation_results)) {

  n = simulation_results$group_size[i] #getting group size n for the current row
  trials = replicate(10000, birthday_match(n)) 
  simulation_results$probability[i] = mean(trials) #calculating probability by finding the mean
}
```

Making plot
```{r}
ggplot(simulation_results, aes(x = group_size, y = probability)) +
  geom_line(color = "blue") +
  geom_point(color = "blue") +
  labs(
    title = "The Birthday Problem: Simulation Results",
    subtitle = paste("Based on 10,000 trials per group size"),
    x = "Number of People in Group",
    y = "Probability of at Least One Shared Birthday"
  )
```

Based on this plot, we can see that the probability of at least two people in the group sharing a birthday steadily increases as the number of people in the group increases and almost 100% chance when there are 50 people in a group.


## Problem 2

Setting design elements
```{r}
n_sample = 30        
sigma = 5       
mu = c(0,1,2,3,4,5,6)     
n_sims = 5000
alpha_level = 0.05 


sim_mean_sd = function(n, mu, sigma) {
  
  sim_data = rnorm(n = n, mean = mu, sd = sigma)
  result = t.test(sim_data, mu = 0)
  
  return(broom::tidy(result))
}

#iterating for 5000 datasets for each mu
sim_results = map_dfr(mu, function(mu_value) {
  sims_mu_value = map_dfr(1:n_sims, 
                          ~sim_mean_sd(
                            n = n_sample,
                            mu = mu_value,
                            sigma = sigma
  )) |> 
    mutate(mean = mu_value)
  
}) |> 
  select(mean, estimate, p.value)

```













